### ISSUE TITLE
ERROR of Install the package

### ISSUE THREAD

**Issue by spark-ck** [ebadi/python-esmini#5]
#4 Hello. 
I just need to use 'esmini' recently. But because my C++ability is too weak, I can only choose to start from Python. I am very happy to have such a project as  'python-esmini'. However, I cannot complete  'Install the package'  in any case.
The error code is the following sentence：
`
pip3 install .
`

#4 The error message is too long, I only intercepted the first few sentences：
`
   error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1

`

## I would appreciate your help

pyhton：3.8.10
ubuntu:：20.04

**Comment by spark-ck** [comment]
The error information is in the following log file：
[error.log](https://github.com/ebadi/python-esmini/files/10193741/error.log)

**Comment by ebadi** [comment]
Hi, this repo is not production level ready but your issue is probably related to your network/proxy or the way curl/TLS libraries work:  
```
      fatal: unable to access 'https://github.com/pybind/pybind11.git/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.
      Cloning into 'pybind11-src'...
      error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
      fatal: the remote end hung up unexpectedly
      fatal: early EOF
      fatal: index-pack failed
```
